Fix/04 2024 create schedule bug
worldwayii/kcontrack-tailwind pull request #1
Opened 2024-04-20 14:38 UTC by solomoreal

## Handle all the 500 errors
## Boldin Create schedule form inputs
## Dynamically populate schedule end time based on start time
## Add 60mind to break option
## Prevent showing Employees from other companies
## Add active class to active sidebar nav item

2024-04-21 08:13 UTC, worldwayii commented on app/Livewire/CreateSchedule.php
> +    public function updatedStartAt($value)
could you explain the need for this new method? and what it does?

2024-04-21 08:22 UTC, worldwayii commented on app/Livewire/CreateScheduleBulk.php
> +    public function updatedStartAt($value)
What does this `updatedStartAt($value)` have in common with the one the `CreateSchedule` class?  They look same to me... Can we DRY thing up? Have method as a helper or trait and have the both classes use them

2024-04-21 08:22 UTC, worldwayii commented on app/Livewire/CreateScheduleDirect.php
> +    public function updatedStartAt($value)
Just like the comment above, this is the 3 time `updatedStartAt($value)` has appeared. Please refactor as suggested above

2024-04-21 08:22 UTC, worldwayii commented on app/Livewire/EditSchedule.php
> +    public function updatedStartAt($value)
4th time, updatedStartAt($value) has appeared. Please refactor as suggested abov

2024-04-21 09:00 UTC, worldwayii commented on app/Livewire/CreateScheduleBulk.php
> +    public function updatedStartAt($value)
This will mean if you need to make changes in ther future, it gets made in on class and not risking making it different places..

2024-04-21 09:02 UTC, worldwayii requested changes
Nice work overall, DRY of the mentioned concerns and we're good to go

2024-04-21 09:13 UTC, solomoreal commented on app/Livewire/CreateSchedule.php
> +    public function updatedStartAt($value)
the update startAt method takes the time in the staartat an then use it to adjust the time in the end at to start from one hour after the startat, lets say I select 9am for start time then end time will start counting from 10am upwards

2024-04-21 09:15 UTC, solomoreal commented on app/Livewire/EditSchedule.php
> +    public function updatedStartAt($value)
noted I will extract the method into a trait

2024-04-22 20:39 UTC, closed without merging

2024-04-22 20:39 UTC, worldwayii commented
Changes now address in https://github.com/worldwayii/kcontrack-tailwind/pull/2