Feature/07 2024 add scheduler checkin
worldwayii/kcontrack-tailwind pull request #24
Opened 2024-07-01 17:24 UTC by solomoreal

## Add API Check-in-Checkout Feature For Scheduler
- add check-in and checkout time to the scheduler model
- create checking/checkout routes and controller Methods
- write test

2024-07-02 11:20 UTC, worldwayii requested changes

2024-07-02 11:20 UTC, worldwayii commented on app/Http/API/V1/Controllers/SchedulerController.php
> +    {
Then in the method, we $this->authorize(auth()->user(), $scheduler)

2024-07-02 11:20 UTC, worldwayii commented on app/Models/Scheduler.php
> +    public function checkInTime(){
This is very superficial but improves readability please can we always have the open braces in the next line? 
`public function checkInTime()`
`{`
`}`

2024-07-02 11:20 UTC, worldwayii commented on routes/api.php
> +        Route::put('checkin/{scheduler}', 'checkIn')->name('scheduler.checkin');
can the name be `schedule.checkin` & `scheduler.checkout` (singular)?

2024-07-02 11:55 UTC, solomoreal commented on app/Http/API/V1/Controllers/SchedulerController.php
> +
noted, I will go with option 2 for now, we can update it when the necessary changes are made to the UI

2024-07-02 11:55 UTC, solomoreal commented on app/Models/Scheduler.php
> +    public function checkInTime(){
noted

2024-07-02 12:01 UTC, solomoreal commented on app/Http/API/V1/Controllers/SchedulerController.php
> +    {
noted

2024-07-04 09:31 UTC, worldwayii commented on app/Http/API/V1/Controllers/SchedulerController.php
> +        if (request()->user()->cannot('update', $scheduler)) {
can you use `$this->authorize('update', $scheduler)` ( checkOut/ checkIn) in you  policy checks rather?
it's a shorter syntax and works fine. You can add test coverage for wrong user to see if the policy check catches them?

2024-07-04 09:51 UTC, worldwayii commented on app/Http/API/V1/Controllers/SchedulerController.php
> +        return [
what is the need for this return with empty string `' '` message? Just return `true`?

2024-07-04 09:59 UTC, worldwayii commented on tests/Integration/Http/API/V1/Controllers/SchedulerControllerTest.php
> +
NIce test coverage, can we have one or 2 to cover policy check? ` testCheckOutFailsIfWhenUserIsWorng` && `` testCheckInFailsIfWhenUserIsWorng``

2024-07-04 21:36 UTC, worldwayii approved these changes

2024-07-04 21:36 UTC, merged