Feature/04 2024 complete add employee
worldwayii/kcontrack-tailwind pull request #4
Opened 2024-04-24 19:44 UTC by solomoreal

## Complete add employees
- handle CSV upload and processing
- handle manual add employee
- send a welcome email to the employee
- update the email template

2024-04-25 22:17 UTC, worldwayii requested changes
Also Can we address the changes  mentioned on whatsapp? When creating and employee with form and it fails, errors don get flashed.

Nice work overall sir

2024-04-25 22:17 UTC, worldwayii commented on resources/views/livewire/create-employers.blade.php
>                                <option selected>Enter range</option>
Can we please make this configurable? also `Employee Position/ Job Role` as well? Bearing in mind this job role can grow 6 to 50+ tomorrow?

2024-04-25 22:17 UTC, worldwayii commented on resources/views/emails/employee/created.blade.php
> +      tailwind.config = {
is there a need for this? we already have a tailwind.config in the project

2024-04-25 22:17 UTC, worldwayii commented on resources/views/emails/employee/created.blade.php
> +    <style>
can this style belong to the app.css and pulled in here? so it it re-useable?

2024-04-26 00:12 UTC, solomoreal commented
> Also Can we address the changes mentioned on whatsapp? When creating and employee with form and it fails, errors don get flashed.
> 
> Nice work overall sir

handled

2024-04-26 00:13 UTC, solomoreal commented on resources/views/emails/employee/created.blade.php
> +    <style>
> can this style belong to the app.css and pulled in here? so it it re-useable?

handled

2024-04-26 00:15 UTC, solomoreal commented on resources/views/livewire/create-employers.blade.php
>                                <option selected>Enter range</option>
done

2024-04-26 00:15 UTC, solomoreal commented on resources/views/emails/employee/created.blade.php
> +      tailwind.config = {
done

2024-04-26 00:15 UTC, solomoreal commented on resources/views/emails/employee/created.blade.php
> +    <style>
done

2024-04-27 16:09 UTC, merged